### ISSUE TITLE
When release for Rui5 or Android U

### ISSUE THREAD

**Issue by yograjfire18** [realme-kernel-opensource/realme_GTneo2-Q5pro-GTMasterExploratory-AndroidT-vendor-source#2]
realme is being so retard to be honest. Never seen such retard actions.
We have got rui 5 already but realme hasn't released the rui5 kernels sources yet.
Even OnePlus 9r sources were out months ago for Android U.

**Comment by realme-kernel-opensource** [comment]
Dear Customer,
We have released the kernel source of the realme Q5 Pro Android U, you can get it from: https://github.com/realme-kernel-opensource/realme_gt_master_exploratory_realme_Q5_Pro_GT-Neo3T-AndroidU-kernel-source & https://github.com/realme-kernel-opensource/realme_gt_master_exploratory_realme_Q5_Pro_GT-Neo3T-AndroidU-vendor-source.

**Comment by yograjfire18** [comment]
thnx for the reply and the source.
But still i see only new device addition.
source for our 3t isn't updated. It is just the file permissions are changed
